// Restaurant data - Edit this file to add more restaurants
const restaurants = [
  {
    id: 1,
    name: "小满飯糰",
    englishName: "Xiaoman Riceburrito",
    address: "573 E El Camino Real, Sunnyvale, CA",
    lat: 37.3688,
    lng: -122.0363,
    cuisine: "Taiwanese Breakfast",
    category: "restaurant",
    topDishes: ["Fan Tuan (Rice Burrito)", "Soy Milk", "Egg Pancake"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 2,
    name: "京味轩",
    englishName: "Taste Good Beijing Cuisine",
    address: "76 S Abel St, Milpitas, CA",
    lat: 37.4323,
    lng: -121.9007,
    cuisine: "Beijing / Northern Chinese",
    category: "restaurant",
    topDishes: ["Zha Jiang Mian", "Peking Duck", "Lamb Skewers"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 3,
    name: "天惠居",
    englishName: "Famous Food Restaurant",
    address: "872 Old San Francisco Rd, Sunnyvale, CA 94086",
    lat: 37.3564,
    lng: -122.0206,
    cuisine: "Tianjin-style Chinese",
    category: "restaurant",
    topDishes: ["Jianbing", "Goubuli Baozi", "Tianjin Pancake"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 4,
    name: "Keke's Breakfast Cafe",
    englishName: "Keke's Breakfast Cafe",
    address: "311 S Mathilda Ave, Sunnyvale, CA 94086",
    lat: 37.3722,
    lng: -122.0307,
    cuisine: "American Breakfast",
    category: "restaurant",
    topDishes: ["Eggs Benedict", "French Toast", "Pancakes"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 5,
    name: "杨国福麻辣烫",
    englishName: "YGF Malatang Noodles & Pots",
    address: "19672 Stevens Creek Blvd, Cupertino, CA",
    lat: 37.3230,
    lng: -122.0098,
    cuisine: "Malatang / Hot Pot",
    category: "restaurant",
    topDishes: ["Customize Malatang", "Bone Broth Base", "Wide Noodles"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 6,
    name: "张亮麻辣烫",
    englishName: "Zhangliang Malatang",
    address: "246 Castro St, Mountain View, CA 94041",
    lat: 37.3940,
    lng: -122.0790,
    cuisine: "Malatang / Hot Pot",
    category: "restaurant",
    topDishes: ["Signature Malatang", "Sesame Sauce Base", "Tofu Skin"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 7,
    name: "小香牛骨米粉",
    englishName: "Hunan Mifen",
    address: "592 E El Camino Real, Sunnyvale, CA 94087",
    lat: 37.3691,
    lng: -122.0336,
    cuisine: "Hunan Rice Noodles",
    category: "restaurant",
    topDishes: ["Beef Bone Rice Noodles", "Spicy Pork Mifen", "Pickled Bean Noodles"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 8,
    name: "自选麻辣烫",
    englishName: "Mala Town",
    address: "438 Barber Ln, Milpitas, CA 95035",
    lat: 37.4165,
    lng: -121.9225,
    cuisine: "Malatang / Hot Pot",
    category: "restaurant",
    topDishes: ["DIY Malatang", "Spicy Broth", "Fresh Vegetables"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 9,
    name: "Dana包子铺",
    englishName: "Danacious Dumplings",
    address: "375 Saratoga Ave M, San Jose, CA",
    lat: 37.3195,
    lng: -121.9680,
    cuisine: "Chinese Dumplings / Baozi",
    category: "restaurant",
    topDishes: ["Pork Baozi", "Pan-Fried Dumplings", "Shengjian Bao"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 10,
    name: "川悦麻辣烫",
    englishName: "CUANYUE Mala Moment",
    address: "1036 E El Camino Real, Sunnyvale, CA 94087",
    lat: 37.3521,
    lng: -122.0055,
    cuisine: "Malatang / Hot Pot",
    category: "restaurant",
    topDishes: ["Sichuan Malatang", "Mala Dry Pot", "Hand-Pulled Noodles"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 11,
    name: "The Skewer Bar",
    englishName: "The Skewer Bar",
    address: "3082 Landess Ave, San Jose, CA 95132",
    lat: 37.4076,
    lng: -121.8585,
    cuisine: "Chinese BBQ Skewers",
    category: "restaurant",
    topDishes: ["Lamb Skewers", "Grilled Chicken Wings", "Cumin Beef"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 12,
    name: "やよい軒",
    englishName: "Yayoi",
    address: "20684 Homestead Rd, Cupertino, CA 95014",
    lat: 37.3411,
    lng: -122.0190,
    cuisine: "Japanese Teishoku",
    category: "restaurant",
    topDishes: ["Chicken Nanban", "Hamburg Steak Set", "Ginger Pork"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 13,
    name: "Popeyes",
    englishName: "Popeyes Louisiana Kitchen",
    address: "816 W El Camino Real, Sunnyvale, CA 94087",
    lat: 37.3688,
    lng: -122.0492,
    cuisine: "American Fast Food / Fried Chicken",
    category: "restaurant",
    topDishes: ["Chicken Sandwich", "Spicy Tenders", "Red Beans & Rice"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 14,
    name: "McDonald's",
    englishName: "McDonald's",
    address: "1060 E El Camino Real, Sunnyvale, CA 94087",
    lat: 37.3509,
    lng: -122.0030,
    cuisine: "American Fast Food",
    category: "restaurant",
    topDishes: ["Big Mac", "McNuggets", "McFlurry"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 15,
    name: "塔里木新疆风味",
    englishName: "Tarim Garden Xinjiang Cuisine",
    address: "768 Barber Ln, Milpitas, CA 95035",
    lat: 37.4185,
    lng: -121.9178,
    cuisine: "Xinjiang / Uyghur Chinese",
    category: "restaurant",
    topDishes: ["Da Pan Ji", "Lamb Skewers", "Hand-Pulled Noodles"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 16,
    name: "川湘小馆",
    englishName: "Hunan Szechuan Cuisine",
    address: "1350 Grant Rd, Mountain View, CA 94040",
    lat: 37.3942,
    lng: -122.0952,
    cuisine: "Hunan / Szechuan Chinese",
    category: "restaurant",
    topDishes: ["Spicy Fish Fillet", "Mapo Tofu", "Cumin Lamb"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 17,
    name: "花溪米粉王",
    englishName: "Mifen101",
    address: "841 Villa St, Mountain View, CA 94041",
    lat: 37.3939,
    lng: -122.0795,
    cuisine: "Guizhou Rice Noodles",
    category: "restaurant",
    topDishes: ["Huaxi Beef Mifen", "Suan Tang Mifen", "Spicy Pork Intestine Noodles"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  // =====================================================
  // Popular / Trending (from r/bayarea & local food blogs)
  // =====================================================
  {
    id: 18,
    name: "鼎泰丰",
    englishName: "Din Tai Fung",
    address: "2855 Stevens Creek Blvd #1259, Santa Clara, CA 95050",
    lat: 37.3241,
    lng: -121.9464,
    cuisine: "Taiwanese / Soup Dumplings",
    category: "restaurant",
    topDishes: ["Xiaolongbao", "Shrimp Fried Rice", "Pork Chop"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 19,
    name: "Dishdash",
    englishName: "Dishdash",
    address: "190 S Murphy Ave, Sunnyvale, CA 94086",
    lat: 37.3761,
    lng: -122.0302,
    cuisine: "Middle Eastern / Mediterranean",
    category: "restaurant",
    topDishes: ["Lamb Shank", "Hummus Plate", "Chicken Shawarma"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 20,
    name: "Chelokababi",
    englishName: "Chelokababi Persian Cuisine",
    address: "1236 S Wolfe Rd, Sunnyvale, CA 94086",
    lat: 37.3537,
    lng: -122.0135,
    cuisine: "Persian",
    category: "restaurant",
    topDishes: ["Koobideh Kabab", "Joojeh Kabab", "Ghormeh Sabzi"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 21,
    name: "Zareen's",
    englishName: "Zareen's",
    address: "135 S Murphy Ave, Sunnyvale, CA 94086",
    lat: 37.3771,
    lng: -122.0303,
    cuisine: "Pakistani-Indian",
    category: "restaurant",
    topDishes: ["Chicken Biryani", "Seekh Kabab", "Chappli Kabab"],
    rating: 0,
    notes: "Michelin Guide recommended. New Sunnyvale location opened 2026.",
    dateVisited: ""
  },
  {
    id: 22,
    name: "Oren's Hummus",
    englishName: "Oren's Hummus",
    address: "126 Castro St, Mountain View, CA 94041",
    lat: 37.3948,
    lng: -122.0787,
    cuisine: "Israeli / Mediterranean",
    category: "restaurant",
    topDishes: ["Hummus Masabacha", "Falafel Plate", "Shakshuka"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 23,
    name: "沸腾北京",
    englishName: "Boiling Beijing",
    address: "649 San Mateo Ave, San Bruno, CA 94066",
    lat: 37.6274,
    lng: -122.4115,
    cuisine: "Beijing Chinese / Peking Duck",
    category: "restaurant",
    topDishes: ["Peking Duck", "Zha Jiang Mian", "Scallion Pancakes"],
    rating: 0,
    notes: "Famous for Peking duck carved tableside. KQED best dishes 2025.",
    dateVisited: ""
  },
  // =====================================================
  // Supermarkets
  // =====================================================
  {
    id: 100,
    name: "大华超市",
    englishName: "99 Ranch Market",
    address: "338 Barber Ln, Milpitas, CA 95035",
    lat: 37.4232,
    lng: -121.9170,
    cuisine: "Supermarket / Chinese Grocery",
    category: "supermarket",
    topDishes: ["Hot Deli Roast Duck", "Fresh Seafood", "Chinese Pastries"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 101,
    name: "H Mart",
    englishName: "H Mart (De Anza)",
    address: "1179 S De Anza Blvd, San Jose, CA 95129",
    lat: 37.3043,
    lng: -122.0345,
    cuisine: "Supermarket / Korean Grocery",
    category: "supermarket",
    topDishes: ["Korean Fried Chicken", "Kimbap", "Fresh Banchan"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 102,
    name: "Marina Food",
    englishName: "Marina Food",
    address: "10122 Bandley Dr, Cupertino, CA 95014",
    lat: 37.3247,
    lng: -122.0342,
    cuisine: "Supermarket / Asian Grocery",
    category: "supermarket",
    topDishes: ["BBQ Pork", "Dim Sum To-Go", "Fresh Produce"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 103,
    name: "Tokyo Central",
    englishName: "Tokyo Central (Marukai)",
    address: "19750 Stevens Creek Blvd, Cupertino, CA 95014",
    lat: 37.3219,
    lng: -122.0185,
    cuisine: "Supermarket / Japanese Grocery",
    category: "supermarket",
    topDishes: ["Fresh Bento Boxes", "Onigiri", "Japanese Snacks"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 104,
    name: "韩国超市",
    englishName: "Hankook Supermarket",
    address: "1092 E El Camino Real, Sunnyvale, CA 94087",
    lat: 37.3517,
    lng: -122.0015,
    cuisine: "Supermarket / Korean Grocery",
    category: "supermarket",
    topDishes: ["Korean BBQ Meats", "Fresh Kimchi", "Tteok (Rice Cakes)"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 105,
    name: "永利超市",
    englishName: "Lion Supermarket",
    address: "1838 N Milpitas Blvd, Milpitas, CA 95035",
    lat: 37.4565,
    lng: -121.9103,
    cuisine: "Supermarket / Vietnamese-Asian Grocery",
    category: "supermarket",
    topDishes: ["Banh Mi", "Fresh Pho Noodles", "Vietnamese Coffee"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  // =====================================================
  // Japanese Supermarkets
  // =====================================================
  {
    id: 106,
    name: "ミツワマーケットプレイス",
    englishName: "Mitsuwa Marketplace",
    address: "675 Saratoga Ave, San Jose, CA 95129",
    lat: 37.3146,
    lng: -121.9779,
    cuisine: "Supermarket / Japanese Grocery",
    category: "supermarket",
    topDishes: ["Food Court Ramen", "Fresh Sashimi", "Japanese Snacks"],
    rating: 0,
    notes: "Large Japanese grocery with food court, Kinokuniya bookstore.",
    dateVisited: ""
  },
  {
    id: 107,
    name: "ニジヤマーケット",
    englishName: "Nijiya Market (Mountain View)",
    address: "143 E El Camino Real, Mountain View, CA 94040",
    lat: 37.3787,
    lng: -122.0714,
    cuisine: "Supermarket / Japanese Grocery",
    category: "supermarket",
    topDishes: ["Fresh Sushi Rolls", "Mochi", "Organic Japanese Produce"],
    rating: 0,
    notes: "",
    dateVisited: ""
  },
  {
    id: 108,
    name: "Suruki Supermarket",
    englishName: "Suruki Supermarket",
    address: "71 E 4th Ave, San Mateo, CA 94401",
    lat: 37.5636,
    lng: -122.3237,
    cuisine: "Supermarket / Japanese Grocery",
    category: "supermarket",
    topDishes: ["Fresh Sushi", "Bento Boxes", "House-made Tofu"],
    rating: 0,
    notes: "Family-owned Japanese supermarket. Great fresh sushi and bento.",
    dateVisited: ""
  }
];
